name:                vegaview
version:             0.1.0.0
github:              "augustunderground/vegaview"
license:             BSD3
author:              "Yannick Uhlmann"
maintainer:          "augustunderground@protonmail.com"
copyright:           "2022 Yannick Uhlmann"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/augustunderground/vegaview#readme>

dependencies:
- base >= 4.7 && < 5
- temporary
- unix
- directory
- text
- aeson
- hvega
- webviewhs

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  vegaview-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vegaview

tests:
  vegaview-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vegaview
